// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWztQKWcQ2lzsK6OX1oj5PzCceuLrr04',
    appId: '1:567726148682:web:f1c31428867692ecdd6ab3',
    messagingSenderId: '567726148682',
    projectId: 'stabit-cb2da',
    authDomain: 'stabit-cb2da.firebaseapp.com',
    storageBucket: 'stabit-cb2da.appspot.com',
    measurementId: 'G-2XQG752X53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyRuC742zYrBI1iUZeixQZmaFl8I3KAI',
    appId: '1:567726148682:android:2895ce38a42418c7dd6ab3',
    messagingSenderId: '567726148682',
    projectId: 'stabit-cb2da',
    storageBucket: 'stabit-cb2da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfTF8yXnsF2BH3wkx94303encuELuGto',
    appId: '1:567726148682:ios:f1fc69109b3dbfbedd6ab3',
    messagingSenderId: '567726148682',
    projectId: 'stabit-cb2da',
    storageBucket: 'stabit-cb2da.appspot.com',
    iosClientId: '567726148682-75jrfg7mibk2ldqi0amifno578ti7b8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.stabit1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfTF8yXnsF2BH3wkx94303encuELuGto',
    appId: '1:567726148682:ios:c93db91c9be662a1dd6ab3',
    messagingSenderId: '567726148682',
    projectId: 'stabit-cb2da',
    storageBucket: 'stabit-cb2da.appspot.com',
    iosClientId: '567726148682-0qe8i4avgesid554siq07ute5a59gcav.apps.googleusercontent.com',
    iosBundleId: 'com.example.stabit1.RunnerTests',
  );
}
